# This is a basic workflow to help you get started with Actions

name: global-emissions-cr

# Controls when the workflow will run
on:
  # Triggers the workflow every 5 minutes
  schedule:
    - cron: "*/5 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a set of commands using the runners shell
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: execute py script # run the run.py to get the latest data
        run: |
          pip install requests
          python contract/oracle/carbon-emission-oracle.py
      - name: Run a multi-line script
        working-directory: ./contract
        run: |
          wget https://github.com/near/near-cli-rs/releases/download/0.1.16/near-cli-0.1.16-x86_64-unknown-linux-gnu.tar.gz
          tar xzvf near-cli-0.1.16-x86_64-unknown-linux-gnu.tar.gz
          CarbonEmission=`python oracle/carbon-emission-oracle.py`
          echo $CarbonEmission
          OwnerId="biome.zdefranc.testnet"
          echo $OwnerId
          ./near-cli-0.1.16-x86_64-unknown-linux-gnu/near-cli execute change-method network testnet contract $OwnerId call set_oracle_value '{"oracle_id": "emissions", "val": "5"}' --prepaid-gas '100.000 TeraGas' --attached-deposit '0 NEAR' signer $OwnerId sign-private-key --signer-public-key ed25519:89JPp9Lng5JBZsjyKFzrEeEvqAPbGcQv9keDYpnrpp81 --signer-private-key ed25519:3t7acfMwkK1yzgKX58EaEUVUUkQDaT42oph66G4RUEPXvMCiZAwMSQNZH364PvkGhyyEjPSZcbie1Z4sk13SKYa5 send
          
